services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: student_system
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/student_system
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
    depends_on:
      - db

  frontend:
    build:  ../student-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
